modLoader="javafml"
loaderVersion="[40,)"
license="All Right Reserved"
issueTrackerURL=""
displayURL=""
logoFile="bd_dtn_banner.png"
[[mods]] #mandatory
    modId="betterdogs_dtn"
    version="${file.jarVersion}"
    updateJSONURL="https://raw.githubusercontent.com/Mrblueyeti/BetterDogsForDTN/5a1f7643d862e85c05f1e9cd248c02e7fd1603f6/check_fior_updates/update.json"
    displayName="Better Dogs For DTN"
    credits=""
    authors="MrBlueYeti"
    description="The Better Dogs resource packs, now for Doggy Talents Next."
[[dependencies.betterdogs_dtn]] #optional
    modId="forge"
    mandatory=true
    versionRange="[40.0.18,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.betterdogs_dtn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.betterdogs_dtn]]
    modId="doggytalents"
    mandatory=true
    versionRange="[1.16.0,)"
    ordering="NONE"
    side="BOTH"